CURRENCY_KEYS = frozenset({
    "stock_price",
    "market_cap",
    "market_cap_calc",
    "net_debt",
    "net_debt_change",
    "buyback_volume",
    "sbc",
    "net_buyback",
    "fcf",
    "net_income",
    "dividends",
    "ebitda",
    # Detail-page additions:
    "revenue",
    "eps_diluted",
    "operating_cash_flow",
    "capex",
    "cash_and_equivalents",
    "st_investments",
    "st_debt",
    "lt_debt",
})
