"""value_definitions_and_company_values

Revision ID: 82bf9e484a46
Revises: 3472d1569d29
Create Date: 2026-04-17 08:57:37.326352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82bf9e484a46'
down_revision = '3472d1569d29'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('value_definitions',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('label_de', sa.String(length=128), nullable=False),
    sa.Column('label_en', sa.String(length=128), nullable=False),
    sa.Column('category', sa.Enum('TRANSACTION', 'BASIC_COMPANY', 'HOHN_BASIC_1', 'HOHN_BASIC_2', 'VALUATION_ADJ', 'RISK_ADJ', 'MGMT_ADJ', 'TOTAL_ADJ', name='valuecategory'), nullable=False),
    sa.Column('source_type', sa.Enum('USER_INPUT', 'API', 'CALCULATED', 'QUALITATIVE', name='sourcetype'), nullable=False),
    sa.Column('data_type', sa.Enum('NUMERIC', 'TEXT', 'FACTOR', name='datatype'), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('company_values',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('value_key', sa.String(length=64), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=True),
    sa.Column('period_type', sa.String(length=16), nullable=False),
    sa.Column('is_forecast', sa.Boolean(), nullable=False),
    sa.Column('numeric_value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('text_value', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('source_name', sa.String(length=128), nullable=True),
    sa.Column('source_link', sa.String(length=512), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('manually_overridden', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['value_key'], ['value_definitions.key'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_values_company_id'), 'company_values', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_values_company_id'), table_name='company_values')
    op.drop_table('company_values')
    op.drop_table('value_definitions')
    # ### end Alembic commands ###
